name: CI
on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run coverage
      - uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build -t jkroepke/github_exporter .
      - run: docker run --rm jkroepke/github_exporter --version
